[project]
name = "bd-mini-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["kafka-python-ng>=2.2.2", "pandas>=2.3.3", "pyspark==3.5.3"]
